### ISSUE TITLE
For yield returning more than one Node causes GC overhead limit exceeded

### ISSUE THREAD

**Issue by hussachai** [GlasslabGames/html.scala#97]
**Dependencies**
- OS: Mac 10.14 (Mojave)
- Java Zulu JDK: 8.30.0.1-macosx
- SBT: 1.3.7
- scalajs: 1.2.0
- Binding + html.scala: latest

**Steps to reproduce**
```
{ for (conversation <- conversations) yield {
<div id="1"></div><div id="2"></div>
}}
```

Currently, my workaround is to wrap those sequence of elements in <div> 

This is the stacktrace
```
java.lang.OutOfMemoryError: GC overhead limit exceeded

  | => hat scala.runtime.IntRef.create(IntRef.java:23)
	at scala.util.hashing.MurmurHash3.unorderedHash(MurmurHash3.scala:93)
	at scala.util.hashing.MurmurHash3$.setHash(MurmurHash3.scala:230)
	at scala.collection.GenSetLike.hashCode(GenSetLike.scala:135)
	at scala.collection.GenSetLike.hashCode$(GenSetLike.scala:135)
	at scala.collection.AbstractSet.hashCode(Set.scala:51)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:68)
	at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:215)
	at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:149)
	at scala.Tuple2.hashCode(Tuple2.scala:24)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.collection.immutable.HashMap.elemHashCode(HashMap.scala:87)
	at scala.collection.immutable.HashMap.computeHash(HashMap.scala:96)
	at scala.collection.immutable.HashMap.updated(HashMap.scala:62)
	at scala.collection.immutable.Map$Map4.updated(Map.scala:227)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:228)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:200)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:32)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:28)
	at scala.collection.TraversableLike.$anonfun$groupBy$4(TraversableLike.scala:415)
	at scala.collection.TraversableLike$$Lambda$505/1556162268.apply(Unknown Source)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
	at scala.collection.TraversableLike$WithFilter$$Lambda$401/1152507263.apply(Unknown Source)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashMap$$Lambda$506/1650332494.apply(Unknown Source)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
	at scala.collection.TraversableLike.groupBy(TraversableLike.scala:414)
Exception in thread "task-progress-report-thread" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at sbt.internal.util.ObjectEvent.toString(ObjectEvent.scala:19)
	at java.lang.String.valueOf(String.java:2994)
	at org.apache.logging.log4j.message.ObjectMessage.getFormattedMessage(ObjectMessage.java:55)
	at org.apache.logging.log4j.core.async.InternalAsyncUtil.makeMessageImmutable(InternalAsyncUtil.java:41)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.setMessage(MutableLogEvent.java:220)
	at org.apache.logging.log4j.core.impl.ReusableLogEventFactory.createEvent(ReusableLogEventFactory.java:80)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:404)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1827)
	at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1613)
	at sbt.internal.util.ManagedLogger.logEvent(ManagedLogger.scala:53)
	at sbt.internal.TaskProgress.report0$1(TaskProgress.scala:116)
	at sbt.internal.TaskProgress.sbt$internal$TaskProgress$$report(TaskProgress.scala:125)
	at sbt.internal.TaskProgress$ProgressThread.run(TaskProgress.scala:36)
```

**Comment by Atry** [comment]
What is the Scala version?

**Comment by hussachai** [comment]
2.13.3

**Comment by hussachai** [comment]
I have another issue that is related to this. Not sure that it is caused by the same bug.

If there is an unrecognized attribute in a tag, this GC overhead limit will be thrown as well.
```
<li class="active"><a href="#A" data-toggle="tab">Summary</a></li>
```
From the above snippet, `data-toggle` will cause the GC issue.
The solution is adding `data:` prefix to that attribute, but I think this kind of error should be handled.

**Comment by Atry** [comment]
Does this bug affect Scala 2.12?

Hussachai Puripunpinyo <notifications@github.com> 于2020年10月14日周三 上午11:44写道：

**Comment by Atry** [comment]
Does this bug affect Scala 2.13.1?


Yang, Bo <pop.atry@gmail.com> 于2020年10月14日周三 下午12:26写道：

**Comment by hussachai** [comment]
I'm not sure about 2.12. I'm using Scala.js 1.2 and html.scala is not crossed compile for Scala.js 1.2 and Scala 2.12

This is the error I got `Error downloading org.lrng.binding:html_sjs1_2.12:latest.release`

Let me try 2.13.1

**Comment by hussachai** [comment]
It works fine for 2.13.1 👍

**Comment by Atry** [comment]
Maybe related to https://github.com/scala/bug/issues/12021

Hussachai Puripunpinyo <notifications@github.com> 于2020年10月14日周三 下午12:38写道：

**Comment by hussachai** [comment]
ok, looks like it will be fixed in Scala 2.13.4.  I will close this issue. Thank you.

**Comment by Atry** [comment]
It should have been fixed in 2.13.3. Since it's not actually fixed, I don't
think 2.13.4 would be any better.
Hussachai Puripunpinyo <notifications@github.com> 于2020年10月14日周三 下午1:01写道：

**Comment by hussachai** [comment]
You're right. The supposedly fix was merged before 2.13.3. 
Actually, the issue you mentioned was Stackoverflow, but this issue is more like consuming too much heap space.
Should I re-open this issue?

**Comment by Atry** [comment]
I think it's a regression in Scala, which could be reported at
https://github.com/scala/bug

Hussachai Puripunpinyo <notifications@github.com> 于2020年10月14日周三 下午6:17写道：

**Comment by hussachai** [comment]
Fair enough. Thank you.
